export const menuData = [
  {
    id: 1,
    category: "Burgers",
    name: "Royal Cheese Burger with extra Fries",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium",
    price: 23.10,
    image: "./images/burger.png",
  },
  {
    id: 2,
    category: "Burgers",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/burger.png",
  },
  {
    id: 3,
    category: "Burgers",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/burger.png",
  },
  {
    id: 4,
    category: "Burgers",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/burger.png",
  },
  {
    id: 5,
    category: "Burgers",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/burger.png",
  },
  {
    id: 6,
    category: "Burgers",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/burger.png",
  },
  {
    id: 7,
    category: "Fries",
    name: "Royal Cheese Burger with extra Fries",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium",
    price: 23.10,
    image: "./images/fries-1.png",
  },
  {
    id: 8,
    category: "Fries",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/fries-1.png",
  },
  {
    id: 9,
    category: "Fries",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/fries-1.png",
  },
  {
    id: 10,
    category: "Fries",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/fries-1.png",
  },
  {
    id: 11,
    category: "Fries",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/fries-1.png",
  },
  {
    id: 12,
    category: "Fries",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/fries-1.png",
  },
  {
    id: 13,
    category: "Cold Drinks",
    name: "Royal Cheese Burger with extra Fries",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium",
    price: 23.10,
    image: "./images/drink-1.png",
  },
  {
    id: 14,
    category: "Cold Drinks",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/drink-2.png",
  },
  {
    id: 15,
    category: "Cold Drinks",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/drink-3.png",
  },
  {
    id: 16,
    category: "Cold Drinks",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/drink-4.png",
  },
  {
    id: 17,
    category: "Cold Drinks",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/drink-5.png",
  },
  {
    id: 18,
    category: "Cold Drinks",
    name: "The classics for 3",
    description: "1 McChicken™, 1 Big Mac™, 1 Royal Cheeseburger, 3 medium sized French Fries, 3 cold drinks",
    price: 23.10,
    image: "./images/drink-6.png",
  },
];

export const reviewsData = [
  {
    id: 1,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was up to the usual McDonald's standard – hot and satisfying.",
    avatar: "./images/profile-pic.png",
  },
  {
    id: 2,
    name: "St Glx",
    location: "South London",
    date: "20th September, 2023",
    rating: 5,
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was up to the usual McDonald's standard – hot and satisfying.",
    avatar: "./images/profile-pic.png",
  },
  {
    id: 3,
    name: "St Glx",
    location: "South London",
    date: "15th September, 2023",
    rating: 5,
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was up to the usual McDonald's standard – hot and satisfying.",
    avatar: "./images/profile-pic.png",
  }
];

// Could also use Map as per instruction "Similar Restaurants List: Display using a Map or object list."
export const similarRestaurants = new Map([
  ["McDonald's London", { image: "mcdonalds", }],
  ["Papa Johns", { image: "papajohns", bg: "bg-green-700" }],
  ["KFC West London", { image: "kfc", bg: "bg-red-500" }],
  ["Texas Chicken", { image: "texas", bg: "bg-orange-500" }],
  ["Burger King", { image: "burgerking", bg: "bg-yellow-500" }],
  ["Shaurma 1", { image: "shaurma", bg: "bg-orange-400" }]
]);
