const matches = [
  {
    id: 1,
    sport: "Football",
    team1: { name: "Manchester United", logo: "🔴" },
    team2: { name: "Liverpool", logo: "🟡" },
    score1: 2,
    score2: 1,
    status: "live",
    minute: 67,
    startTime: new Date().toISOString(),
  },
  {
    id: 2,
    sport: "Cricket",
    team1: { name: "India", logo: "🇮🇳" },
    team2: { name: "Australia", logo: "🇦🇺" },
    score1: 245,
    score2: 198,
    status: "live",
    minute: null,
    over: "34.2",
    startTime: new Date().toISOString(),
  },
  {
    id: 3,
    sport: "Basketball",
    team1: { name: "Lakers", logo: "💜" },
    team2: { name: "Warriors", logo: "💛" },
    score1: 89,
    score2: 95,
    status: "live",
    quarter: 3,
    minute: 8,
    startTime: new Date().toISOString(),
  },
  {
    id: 4,
    sport: "Football",
    team1: { name: "Real Madrid", logo: "⚪" },
    team2: { name: "Barcelona", logo: "🔵" },
    score1: 3,
    score2: 3,
    status: "finished",
    minute: 90,
    startTime: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 5,
    sport: "Cricket",
    team1: { name: "England", logo: "🏴" },
    team2: { name: "Pakistan", logo: "🇵🇰" },
    score1: 0,
    score2: 0,
    status: "upcoming",
    minute: null,
    startTime: new Date(Date.now() + 7200000).toISOString(),
  },
  {
    id: 6,
    sport: "Basketball",
    team1: { name: "Celtics", logo: "🍀" },
    team2: { name: "Heat", logo: "🔥" },
    score1: 0,
    score2: 0,
    status: "upcoming",
    minute: null,
    startTime: new Date(Date.now() + 3600000).toISOString(),
  },
];

module.exports = matches;
